//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string userName { get; set; }
        public string nickname { get; set; }
        public string pword { get; set; }
        public string mail { get; set; }
        public System.DateTime bdate { get; set; }
        public string avatar { get; set; }
        public string likes { get; set; }
        public string dislikes { get; set; }
        public string hobbies { get; set; }
        public Nullable<int> cityID { get; set; }
        public System.DateTime accountCreationDate { get; set; }
    }
}
